version: "3"

services:
  mysql-development:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TestShopDB
    ports:
      - "3308:3306"
    volumes:
      - mysql-development_data:/var/lib/mysql

volumes:
  mysql-development_data:
